---
- name: Install freenect dependencies
  apt:
    pkg: 
      - ros-{{ ros_release }}-rgbd-launch
      - ros-{{ ros_release }}-camera-info-manager
      - ros-{{ ros_release }}-diagnostic-updater
      - freenect
    state: present

- name: Create catkin workspace dir
  file:
    path: /home/{{ ros_user }}/catkin_ws/src
    state: directory
    mode: '0755'
    owner: "{{ ros_user }}"

- name: Initialize catkin workspace
  command: bash -c "source /opt/ros/{{ ros_release }}/setup.bash; catkin_make"
  args:
    chdir:   /home/{{ ros_user }}/catkin_ws
    creates: /home/{{ ros_user }}/catkin_ws/src/CMakeLists.txt

- name: Download freenect sources
  git:
    repo: "{{ freenect_stack_url }}"
    dest: /home/{{ ros_user }}/catkin_ws/src/freenect
    version: "{{ freenect_stack_ref }}"

- name: Build catkin workspace
  command: bash -c "source /home/{{ ros_user }}/catkin_ws/devel/setup.bash; catkin_make -DCMAKE_INSTALL_PREFIX=/opt/ros/{{ ros_release }} install"
  args:
    chdir:   /home/{{ ros_user }}/catkin_ws
    creates: /opt/ros/{{ ros_release }}/share/freenect_launch/launch/freenect.launch

- name: Create service ros-freenect 
  template:
    src: ros-freenect.service.j2
    dest: /etc/systemd/system/ros-freenect.service
    owner: root
    group: root
    mode: '0644'

- name: roscore systemd service enable and start
  systemd:
    state: started
    enabled: yes
    name: ros-freenect