---
- name: Add ROS repository apt-key
  apt_key:
    url: "{{ ros_apt_key }}"
    state: present

- name: Add ROS repository
  apt_repository:
    repo: "deb {{ ros_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present

- name: Install desired ROS package
  apt:
    pkg: 
      - "ros-{{ ros_release }}-{{ ros_package }}"
      - python-rosdep
      - python-rosinstall
      - python-rosinstall-generator 
      - python-wstool
      - build-essential
    state: present

- name: Initialize rosdep
  command: bash -c "source /opt/ros/{{ ros_release }}/setup.bash; rosdep init"
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list

- name: Update rosdep
  command: bash -c "source /opt/ros/{{ ros_release }}/setup.bash; rosdep init"
  become: yes
  become_user: "{{ ros_user }}"
